version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clj_auth
      POSTGRES_USER: clj_auth
      POSTGRES_PASSWORD: clj_auth_pass
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
